 # Python Assignment: Data Structures,Functions, Numpy & Pandas


 ## Instructions
• Attempt all questions.
• Submit the completed assignment in .ipynb format.
• Use appropriate function definitions and comments for clarity.

    

# Assignment Questions

  ## Section A: Data Structures & Control Structures

### 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [63]:
numbers = [3, 5, 8, 2, 1]

numbers.append(10)
print("Append:", numbers)

numbers.extend([7, 9])
print("Extend:", numbers)

numbers.insert(1, 20)
print("Insert:", numbers)

numbers.remove(2)
print("Remove:", numbers)

numbers.pop()
print("Pop:", numbers)

print("Index of 8:", numbers.index(8))

print("Count of 2:", numbers.count(2))

numbers.sort()
print("Sort:", numbers)

numbers.reverse()
print("Reverse:", numbers)

numbers.clear()
print("Clear:", numbers)

Append: [3, 5, 8, 2, 1, 10]
Extend: [3, 5, 8, 2, 1, 10, 7, 9]
Insert: [3, 20, 5, 8, 2, 1, 10, 7, 9]
Remove: [3, 20, 5, 8, 1, 10, 7, 9]
Pop: [3, 20, 5, 8, 1, 10, 7]
Index of 8: 3
Count of 2: 0
Sort: [1, 3, 5, 7, 8, 10, 20]
Reverse: [20, 10, 8, 7, 5, 3, 1]
Clear: []


 ### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
        Once a tuple is created, its values cannot be changed.

In [64]:
# Create a tuple
students = ("Ankit", "Rahul", "Aman")
print("Original Tuple:", students)

#Why?
#A tuple is immutable.
#Immutable means:
#Once a tuple is created, its values cannot be changed.


Original Tuple: ('Ankit', 'Rahul', 'Aman')


  ### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [65]:
numbers = {1, 2, 2, 3, 4, 4, 5}

print(numbers)
#Why?
#A set does not allow duplicate values.


{1, 2, 3, 4, 5}


### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [66]:
student = {
    "name": "Ankit",
    "age": 22,
    "city": "Patna"
}

student["age"] = 23

student["email"] = "ankit@gmail.com"

print(student)

{'name': 'Ankit', 'age': 23, 'city': 'Patna', 'email': 'ankit@gmail.com'}


### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [67]:
age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


### 6. Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [68]:
marks = 85

if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail")

B


### 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [69]:
num = 8

if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Positive and Even


# Section B: Numpy

### 8. Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [70]:
import numpy as np
#A scalar using np.array(5)
scalar = np.array(5)
print(scalar)

#A 1D array with values 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
#A 2D array (2x3) with values from 10 to 60 in steps of 10

arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr2)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().


In [71]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))
print(random_array)

[[17  8 65  4]
 [18 40 45 33]
 [31 62 45 60]
 [68 15 94 64]]


### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [72]:
import numpy as np
import pandas as pd

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

df = pd.DataFrame(arr, columns=["A", "B", "C"])

print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


# Section C: Exploring Pandas

### 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:

- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [73]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ankit", "Rahul", "Aman", "Ravi", "Neha",
             "Priya", "Karan", "Sahil", "Pooja", "Ankit"],
    
    "Age": [21, 22, 20, 23, 21, 24, 22, 25, 23, 21],
    
    "City": ["Patna", "Delhi", "Mumbai", "Patna", "Delhi",
             "Kolkata", "Mumbai", "Delhi", "Patna", "Patna"],
    
    "Salary": [25000, 30000, np.nan, 28000, 32000,
               35000, np.nan, 40000, 30000, 25000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age     City   Salary
0  Ankit   21    Patna  25000.0
1  Rahul   22    Delhi  30000.0
2   Aman   20   Mumbai      NaN
3   Ravi   23    Patna  28000.0
4   Neha   21    Delhi  32000.0
5  Priya   24  Kolkata  35000.0
6  Karan   22   Mumbai      NaN
7  Sahil   25    Delhi  40000.0
8  Pooja   23    Patna  30000.0
9  Ankit   21    Patna  25000.0


In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [75]:
df.describe()


,Age,Salary
count,10.000000,8.000000
mean,22.200000,30625.000000
std,1.549193,5069.164485
min,20.000000,25000.000000
25%,21.000000,27250.000000
50%,22.000000,30000.000000
75%,23.000000,32750.000000
max,25.000000,40000.000000


In [76]:
print(df[["Name", "City"]])

    Name     City
0  Ankit    Patna
1  Rahul    Delhi
2   Aman   Mumbai
3   Ravi    Patna
4   Neha    Delhi
5  Priya  Kolkata
6  Karan   Mumbai
7  Sahil    Delhi
8  Pooja    Patna
9  Ankit    Patna


In [77]:
df = df.drop("City", axis=1)

print(df)

    Name  Age   Salary
0  Ankit   21  25000.0
1  Rahul   22  30000.0
2   Aman   20      NaN
3   Ravi   23  28000.0
4   Neha   21  32000.0
5  Priya   24  35000.0
6  Karan   22      NaN
7  Sahil   25  40000.0
8  Pooja   23  30000.0
9  Ankit   21  25000.0


In [78]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df["Salary"].mean()

np.float64(30625.0)

In [79]:
df = df.drop_duplicates()

print(df)

    Name  Age   Salary
0  Ankit   21  25000.0
1  Rahul   22  30000.0
2   Aman   20  30625.0
3   Ravi   23  28000.0
4   Neha   21  32000.0
5  Priya   24  35000.0
6  Karan   22  30625.0
7  Sahil   25  40000.0
8  Pooja   23  30000.0
